name: SYNC for OpenStack

# weekly job
on:
    # for manually trigger
    workflow_dispatch:
    schedule:
        -
            cron: 0 0 * * 0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "sync-from-upstream"
    sync-from-upstream:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -
                uses: actions/checkout@v2

            # Setup git
            -
                name: Setup Git Infomation
                run: |
                    git config --global user.name 'mystic'
                    git config --global user.email '215104920@qq.com'
            -
                name: Syncing
                run: |
                    git submodule update --init --remote --recursive --jobs 9
                    git submodule foreach git checkout master
                    git submodule foreach --recursive git pull --rebase --prune
                    git commit -am "Sync: `date +'%F %T %z'`"
                    git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
